# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- goos:
  - linux
  - windows
  goarch:
  - amd64
archive:
  format: zip
s3:
-
  bucket: d2l-terraform-registry
  region: us-east-1
  folder: "providers/terraform-provider-shell/{{.Version}}"